extends Node2D

var slowdown1 = preload("res://Art/Tilesheets/colored-transparent_packed.png")
var slowdown12 = preload("res://Art/Tilesheets/colored-transparent_packed.png")
var slowdown11 = preload("res://Art/Tilesheets/colored-transparent_packed.png")
var slowdown612 = preload("res://Art/Tilesheets/colored-transparent_packed.png")
var slowdown121 = preload("res://Art/Tilesheets/colored-transparent_packed.png")
var slowdown112421 = preload("res://Art/Tilesheets/colored-transparent_packed.png")
var slowdown112312 = preload("res://Art/Tilesheets/colored-transparent_packed.png")
var slowdown112321313 = preload("res://Art/Tilesheets/colored-transparent_packed.png")
var slowdown1123123 = preload("res://Art/Tilesheets/colored-transparent_packed.png")
var slowdown1554 = preload("res://Art/Tilesheets/colored-transparent_packed.png")
var slowdown1333 = preload("res://Art/Tilesheets/colored-transparent_packed.png")
var slowdown1444 = preload("res://Art/Tilesheets/colored-transparent_packed.png")
var slowdown1222 = preload("res://Art/Tilesheets/colored-transparent_packed.png")
var slowdown1111 = preload("res://Art/Tilesheets/colored-transparent_packed.png")
var slowdown16766 = preload("res://Art/Tilesheets/colored-transparent_packed.png")
var slowdown7887 = preload("res://Art/Tilesheets/colored-transparent_packed.png")
var slowdown8871 = preload("res://Art/Tilesheets/colored-transparent_packed.png")
var slowdown78781 = preload("res://Art/Tilesheets/colored-transparent_packed.png")
var slowdown78871 = preload("res://Art/Tilesheets/colored-transparent_packed.png")
var slowdown7887981 = preload("res://Art/Tilesheets/colored-transparent_packed.png")
